---
swagger: "2.0"
info:
  description: "This is a simple API"
  version: "1.0.0"
  title: "Simple Inventory API"
  contact:
    email: "you@your-company.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/robipolli/indicepa/1.0.0"
tags:
- name: "admins"
  description: "Secured Admin-only calls"
- name: "developers"
  description: "Operations available to regular developers"
schemes:
- "https"
- "http"
security:
- AuthorizationHeader: []
paths:
  /amministrazioni:
    get:
      tags:
      - "developers"
      summary: "searches amministrazioni"
      description: "By passing in the appropriate options, you can search for\navailable\
        \ inventory in the system\n"
      operationId: "get_amministrazione"
      produces:
      - "application/json"
      parameters:
      - name: "cod_amm"
        in: "query"
        description: "COD_AMM"
        required: true
        type: "string"
        x-example: "c_c143"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            $ref: "#/definitions/WS05Response"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.developers_controller"
  /amministrazioni-aoo:
    get:
      tags:
      - "developers"
      summary: "searches amministrazioni"
      description: "By passing in the appropriate options, you can search for\navailable\
        \ inventory in the system\n"
      operationId: "search_amministrazioni_aree_organizzative_omogenee"
      produces:
      - "application/json"
      parameters:
      - name: "cod_amm"
        in: "query"
        description: "COD_AMM"
        required: true
        type: "string"
        x-example: "c_c143"
      - name: "cod_aoo"
        in: "query"
        description: "pass an optional search string for looking up inventory"
        required: false
        type: "string"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            $ref: "#/definitions/WS02Response"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.developers_controller"
  /amministrazioni-ou:
    get:
      tags:
      - "developers"
      summary: "searches amministrazioni"
      description: "By passing in the appropriate options, you can search for\navailable\
        \ inventory in the system\n"
      operationId: "search_amministrazioni_unita_organizzative"
      produces:
      - "application/json"
      parameters:
      - name: "cod_amm"
        in: "query"
        description: "COD_AMM"
        required: true
        type: "string"
        x-example: "c_c143"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            $ref: "#/definitions/WS03Response"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.developers_controller"
  /fatturazione-elettronica:
    get:
      tags:
      - "developers"
      summary: "cerca per codice fiscale fatturazione elettronica WS04"
      description: "By passing in the appropriate options, you can search for\navailable\
        \ inventory in the system\n"
      operationId: "search_fatturazione_elettronica"
      produces:
      - "application/json"
      parameters:
      - name: "cod_amm"
        in: "query"
        description: "COD_AMM"
        required: true
        type: "string"
        x-example: "c_c143"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            $ref: "#/definitions/WS04Response"
        400:
          description: "bad input parameter"
        401:
          description: "Forbidden"
      x-swagger-router-controller: "swagger_server.controllers.developers_controller"
  /fatturazione-elettronica-codice-fiscale:
    get:
      tags:
      - "developers"
      summary: "cerca per codice fiscale fatturazione elettronica WS06"
      description: "By passing in the appropriate options, you can search for\navailable\
        \ inventory in the system\n"
      operationId: "search_fatturazione_elettronica_by_tax_code"
      produces:
      - "application/json"
      parameters:
      - name: "codice_fiscale"
        in: "query"
        description: "CF"
        required: true
        type: "string"
        x-example: "00121350086"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            $ref: "#/definitions/WS01Response"
        400:
          description: "bad input parameter"
        401:
          description: "Forbidden"
      x-swagger-router-controller: "swagger_server.controllers.developers_controller"
  /fatturazione-elettronica-ufficio:
    get:
      tags:
      - "developers"
      summary: "cerca per codice fiscale fatturazione elettronica WS06"
      description: "By passing in the appropriate options, you can search for\navailable\
        \ inventory in the system\n"
      operationId: "search_fatturazione_elettronica_by_ufficio"
      produces:
      - "application/json"
      parameters:
      - name: "codice_uni_ou"
        in: "query"
        description: "COD_UNI_OU"
        required: true
        type: "string"
        x-example: "d"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            $ref: "#/definitions/WS06Response"
        400:
          description: "bad input parameter"
        401:
          description: "Forbidden"
      x-swagger-router-controller: "swagger_server.controllers.developers_controller"
securityDefinitions:
  AuthorizationHeader:
    type: "apiKey"
    name: "Authorization"
    in: "header"
definitions:
  Manufacturer:
    required:
    - "name"
    properties:
      name:
        type: "string"
        example: "ACME Corporation"
      homePage:
        type: "string"
        format: "url"
        example: "https://www.acme-corp.com"
      phone:
        type: "string"
        example: "408-867-5309"
  WS05Response:
    properties:
      data:
        $ref: "#/definitions/WS05Response_data"
      result:
        $ref: "#/definitions/WS05Response_result"
    example:
      result:
        num_items: 0.146581298050294517310021547018550336360931396484375
        cod_err: 6.02745618307040320615897144307382404804229736328125
        desc_err: "desc_err"
      data:
        cf: "cf"
        categoria: "categoria"
        indirizzo: "indirizzo"
        nome_resp: "nome_resp"
        provincia: "provincia"
        regione: "regione"
        acronimo: "acronimo"
        tipologia: "tipologia"
        mail4: "mail4"
        mail3: "mail3"
        Referenti:
        - cogn_ref: "cogn_ref"
          nome_ref: "nome_ref"
        - cogn_ref: "cogn_ref"
          nome_ref: "nome_ref"
        cap: "cap"
        mail5: "mail5"
        comune: "comune"
        liv_accessibili: 0.80082819046101150206595775671303272247314453125
        mail2: "mail2"
        data_accreditamento: "data_accreditamento"
        mail1: "mail1"
        sito_istituzionale: "sito_istituzionale"
        cod_amm: "cod_amm"
        cogn_resp: "cogn_resp"
        titolo_resp: "titolo_resp"
        des_amm: "des_amm"
  WS02Response:
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/WS02Response_data"
      result:
        $ref: "#/definitions/WS05Response_result"
    example:
      result:
        num_items: 0.146581298050294517310021547018550336360931396484375
        cod_err: 6.02745618307040320615897144307382404804229736328125
        desc_err: "desc_err"
      data:
      - mail_resp: "mail_resp"
        indirizzo: "indirizzo"
        nome_resp: "nome_resp"
        provincia: "provincia"
        regione: "regione"
        tel_resp: "tel_resp"
        mail3: "mail3"
        cap: "cap"
        comune: "comune"
        mail2: "mail2"
        mail1: "mail1"
        cod_amm: "cod_amm"
        cod_aoo: "cod_aoo"
        tel: "tel"
        cogn_resp: "cogn_resp"
        fax: "fax"
        des_aoo: "des_aoo"
      - mail_resp: "mail_resp"
        indirizzo: "indirizzo"
        nome_resp: "nome_resp"
        provincia: "provincia"
        regione: "regione"
        tel_resp: "tel_resp"
        mail3: "mail3"
        cap: "cap"
        comune: "comune"
        mail2: "mail2"
        mail1: "mail1"
        cod_amm: "cod_amm"
        cod_aoo: "cod_aoo"
        tel: "tel"
        cogn_resp: "cogn_resp"
        fax: "fax"
        des_aoo: "des_aoo"
  WS03Response:
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/WS03Response_data"
      result:
        $ref: "#/definitions/WS05Response_result"
    example:
      result:
        num_items: 0.146581298050294517310021547018550336360931396484375
        cod_err: 6.02745618307040320615897144307382404804229736328125
        desc_err: "desc_err"
      data:
      - cod_uni_ou: "cod_uni_ou"
        mail_resp: "mail_resp"
        indirizzo: "indirizzo"
        nome_resp: "nome_resp"
        provincia: "provincia"
        regione: "regione"
        tel_resp: "tel_resp"
        mail3: "mail3"
        cap: "cap"
        comune: "comune"
        mail2: "mail2"
        mail1: "mail1"
        cod_amm: "cod_amm"
        cod_aoo: "cod_aoo"
        des_ou: "des_ou"
        tel: "tel"
        cogn_resp: "cogn_resp"
        fax: "fax"
      - cod_uni_ou: "cod_uni_ou"
        mail_resp: "mail_resp"
        indirizzo: "indirizzo"
        nome_resp: "nome_resp"
        provincia: "provincia"
        regione: "regione"
        tel_resp: "tel_resp"
        mail3: "mail3"
        cap: "cap"
        comune: "comune"
        mail2: "mail2"
        mail1: "mail1"
        cod_amm: "cod_amm"
        cod_aoo: "cod_aoo"
        des_ou: "des_ou"
        tel: "tel"
        cogn_resp: "cogn_resp"
        fax: "fax"
  WS04Response:
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/WS04Response_data"
      result:
        $ref: "#/definitions/WS05Response_result"
    example:
      result:
        num_items: 0.146581298050294517310021547018550336360931396484375
        cod_err: 6.02745618307040320615897144307382404804229736328125
        desc_err: "desc_err"
      data:
      - cod_uni_ou: "cod_uni_ou"
        cf: "cf"
        dat_val_canale_trasm_sfe: "dat_val_canale_trasm_sfe"
        cod_amm: "cod_amm"
        cod_aoo: "cod_aoo"
        des_ou: "des_ou"
        dt_verifca_cf: "dt_verifca_cf"
        stato_canale: "stato_canale"
      - cod_uni_ou: "cod_uni_ou"
        cf: "cf"
        dat_val_canale_trasm_sfe: "dat_val_canale_trasm_sfe"
        cod_amm: "cod_amm"
        cod_aoo: "cod_aoo"
        des_ou: "des_ou"
        dt_verifca_cf: "dt_verifca_cf"
        stato_canale: "stato_canale"
  WS01Response:
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/WS01Response_data"
      result:
        $ref: "#/definitions/WS05Response_result"
    example:
      result:
        num_items: 0.146581298050294517310021547018550336360931396484375
        cod_err: 6.02745618307040320615897144307382404804229736328125
        desc_err: "desc_err"
      data:
      - OU:
        - cod_uni_ou: "cod_uni_ou"
          des_ou: "des_ou"
          stato_canale: "stato_canale"
        - cod_uni_ou: "cod_uni_ou"
          des_ou: "des_ou"
          stato_canale: "stato_canale"
        cod_amm: "cod_amm"
        des_amm: "des_amm"
      - OU:
        - cod_uni_ou: "cod_uni_ou"
          des_ou: "des_ou"
          stato_canale: "stato_canale"
        - cod_uni_ou: "cod_uni_ou"
          des_ou: "des_ou"
          stato_canale: "stato_canale"
        cod_amm: "cod_amm"
        des_amm: "des_amm"
  WS06Response:
    properties:
      data:
        $ref: "#/definitions/WS06Response_data"
      result:
        $ref: "#/definitions/WS05Response_result"
    example:
      result:
        num_items: 0.146581298050294517310021547018550336360931396484375
        cod_err: 6.02745618307040320615897144307382404804229736328125
        desc_err: "desc_err"
      data:
        cod_uni_ou: "cod_uni_ou"
        cf: "cf"
        mail_resp: "mail_resp"
        indirizzo: "indirizzo"
        nome_resp: "nome_resp"
        provincia: "provincia"
        regione: "regione"
        tel_resp: "tel_resp"
        mail3: "mail3"
        cap: "cap"
        comune: "comune"
        mail2: "mail2"
        mail1: "mail1"
        dat_val_canale_trasm_sfe: "dat_val_canale_trasm_sfe"
        cod_amm: "cod_amm"
        cod_aoo: "cod_aoo"
        des_ou: "des_ou"
        tel: "tel"
        cogn_resp: "cogn_resp"
        dt_verifica_cf: "dt_verifica_cf"
        fax: "fax"
        stato_canale: "stato_canale"
  WS05Response_data_Referenti:
    properties:
      cogn_ref:
        type: "string"
        description: "Cognome del referente dell'Ente"
      nome_ref:
        type: "string"
        description: "Nome del referente dell'Ente"
    example:
      cogn_ref: "cogn_ref"
      nome_ref: "nome_ref"
  WS05Response_data:
    properties:
      Referenti:
        type: "array"
        items:
          $ref: "#/definitions/WS05Response_data_Referenti"
        minItems: 1
      acronimo:
        type: "string"
        description: "Acronimo dell'Ente"
      cap:
        type: "string"
        description: "Cap registrato in IPA per la sede legale dell'Ente"
      categoria:
        type: "string"
        description: "Categoria dell'Ente in IPA"
      cf:
        type: "string"
        description: "Codice fiscale dell'Ente"
      cod_amm:
        type: "string"
        description: "Codice Ente accreditato in IPA"
      cogn_resp:
        type: "string"
        description: "Cognome del responsabile dell'Ente"
      comune:
        type: "string"
        description: "Comune registrato in IPA per la sede legale dell'Ente"
      data_accreditamento:
        type: "string"
        description: "Data di accreditamento dell'Ente"
      des_amm:
        type: "string"
        description: "Denominazione Ente accreditato in IPA"
      indirizzo:
        type: "string"
        description: "Indirizzo postale registrato in IPA per la sede legale dell'Ente"
      liv_accessibili:
        type: "number"
        description: "livello di accessibilità del sito dell'Ente"
      mail1:
        type: "string"
        description: "Indirizzo email primario associato all’Ente di tipo PEC|CECPAC"
      mail2:
        type: "string"
        description: "Indirizzo email associato all’Ente"
      mail3:
        type: "string"
        description: "Indirizzo email associato all’Ente"
      mail4:
        type: "string"
        description: "Indirizzo email primario associato all’Ente"
      mail5:
        type: "string"
        description: "Indirizzo email associato all’Ente"
      nome_resp:
        type: "string"
        description: "Nome del responsabile dell'Ente"
      provincia:
        type: "string"
        description: "Provincia registrata in IPA per la sede legale dell'Ente"
      regione:
        type: "string"
        description: "Regione registrata in IPA per la sede legale dell'Ente"
      sito_istituzionale:
        type: "string"
        description: "Sito istituzionale dell'Ente"
      tipologia:
        type: "string"
        description: "Tipologia dell’Ente in IPA"
      titolo_resp:
        type: "string"
        description: "Titolo del responsabile dell'Ente"
    example:
      cf: "cf"
      categoria: "categoria"
      indirizzo: "indirizzo"
      nome_resp: "nome_resp"
      provincia: "provincia"
      regione: "regione"
      acronimo: "acronimo"
      tipologia: "tipologia"
      mail4: "mail4"
      mail3: "mail3"
      Referenti:
      - cogn_ref: "cogn_ref"
        nome_ref: "nome_ref"
      - cogn_ref: "cogn_ref"
        nome_ref: "nome_ref"
      cap: "cap"
      mail5: "mail5"
      comune: "comune"
      liv_accessibili: 0.80082819046101150206595775671303272247314453125
      mail2: "mail2"
      data_accreditamento: "data_accreditamento"
      mail1: "mail1"
      sito_istituzionale: "sito_istituzionale"
      cod_amm: "cod_amm"
      cogn_resp: "cogn_resp"
      titolo_resp: "titolo_resp"
      des_amm: "des_amm"
  WS05Response_result:
    properties:
      cod_err:
        type: "number"
        description: "Codice di ritorno"
      desc_err:
        type: "string"
        description: "Descrizione errore"
      num_items:
        type: "number"
        description: "Numero di occorrenze trovate"
        minimum: 0
    example:
      num_items: 0.146581298050294517310021547018550336360931396484375
      cod_err: 6.02745618307040320615897144307382404804229736328125
      desc_err: "desc_err"
  WS02Response_data:
    properties:
      cap:
        type: "string"
        description: "Cap registrato in IPA per la sede dell'AOO"
      cod_amm:
        type: "string"
        description: "Codice Ente accreditato in IPA"
      cod_aoo:
        type: "string"
        description: "Codice AOO"
      cogn_resp:
        type: "string"
        description: "Cognome del responsabile dell'AOO"
      comune:
        type: "string"
        description: "Comune registrato in IPA per la sede dell'AOO"
      des_aoo:
        type: "string"
        description: "Nome dell'AOO"
      fax:
        type: "string"
        description: "Numero di fax registrato in IPA per dell’AOO"
      indirizzo:
        type: "string"
        description: "Indirizzo postale registrato in IPA per la sede dell'AOO"
      mail1:
        type: "string"
        description: "Indirizzo email primario associato all’AOO"
      mail2:
        type: "string"
        description: "Indirizzo email associato all’AOO"
      mail3:
        type: "string"
        description: "Indirizzo email associato all’AOO"
      mail_resp:
        type: "string"
        description: "Indirizzo email del responsabile dell'AOO"
      nome_resp:
        type: "string"
        description: "Nome del responsabile dell'AOO"
      provincia:
        type: "string"
        description: "Provincia registrata in IPA per la sede dell'AOO"
      regione:
        type: "string"
        description: "Regione registrata in IPA per la sede dell'AOO"
      tel:
        type: "string"
        description: "Numero di telefono registrato in IPA per dell’AOO"
      tel_resp:
        type: "string"
        description: "Numero di telefono del responsabile dell'AOO"
    example:
      mail_resp: "mail_resp"
      indirizzo: "indirizzo"
      nome_resp: "nome_resp"
      provincia: "provincia"
      regione: "regione"
      tel_resp: "tel_resp"
      mail3: "mail3"
      cap: "cap"
      comune: "comune"
      mail2: "mail2"
      mail1: "mail1"
      cod_amm: "cod_amm"
      cod_aoo: "cod_aoo"
      tel: "tel"
      cogn_resp: "cogn_resp"
      fax: "fax"
      des_aoo: "des_aoo"
  WS03Response_data:
    properties:
      cap:
        type: "string"
        description: "CapregistratoinIPAperlasededell'UO"
      cod_amm:
        type: "string"
        description: "Codice Ente accreditato in IPA"
      cod_aoo:
        type: "string"
        description: "Codice AOO"
      cod_uni_ou:
        type: "string"
        description: "Codice Univoco dell'UO"
      cogn_resp:
        type: "string"
        description: "Cognomedelresponsabiledell'UO"
      comune:
        type: "string"
        description: "ComuneregistratoinIPAperlasededell'UO"
      des_ou:
        type: "string"
        description: "Nome dell'UO"
      fax:
        type: "string"
        description: "NumerodifaxregistratoinIPAperdell’UO"
      indirizzo:
        type: "string"
        description: "IndirizzopostaleregistratoinIPAperlasededell'UO"
      mail1:
        type: "string"
        description: "Indirizzoemailprimarioassociatoall’UO"
      mail2:
        type: "string"
        description: "Indirizzoemailassociatoall’UO"
      mail3:
        type: "string"
        description: "Indirizzoemailassociatoall’UO"
      mail_resp:
        type: "string"
        description: "Indirizzoemaildelresponsabiledell'UO"
      nome_resp:
        type: "string"
        description: "Nomedelresponsabiledell'UO"
      provincia:
        type: "string"
        description: "Provincia registrata in IPA per la sede dell'UO"
      regione:
        type: "string"
        description: "Regione registrata in IPA per la sede dell'UO"
      tel:
        type: "string"
        description: "NumeroditelefonoregistratoinIPAperdell’UO"
      tel_resp:
        type: "string"
        description: "Numeroditelefonodelresponsabiledell'UO"
    example:
      cod_uni_ou: "cod_uni_ou"
      mail_resp: "mail_resp"
      indirizzo: "indirizzo"
      nome_resp: "nome_resp"
      provincia: "provincia"
      regione: "regione"
      tel_resp: "tel_resp"
      mail3: "mail3"
      cap: "cap"
      comune: "comune"
      mail2: "mail2"
      mail1: "mail1"
      cod_amm: "cod_amm"
      cod_aoo: "cod_aoo"
      des_ou: "des_ou"
      tel: "tel"
      cogn_resp: "cogn_resp"
      fax: "fax"
  WS04Response_data:
    properties:
      cf:
        type: "string"
        description: "Codice fiscale del servizio di fatturazione elettronica"
      cod_amm:
        type: "string"
        description: "Codice Ente accreditato in IPA"
      cod_aoo:
        type: "string"
        description: "Codice AOO"
      cod_uni_ou:
        type: "string"
        description: "Codice Univoco dell'Ufficio di fatturazione elettronica"
      dat_val_canale_trasm_sfe:
        type: "string"
        description: "Data di inizio validità del servizio di fatturazione"
      des_ou:
        type: "string"
        description: "Nome dell'UO"
      dt_verifca_cf:
        type: "string"
        description: "Data di validazione del cf"
      stato_canale:
        type: "string"
        description: "Stato del canale di fatturazione"
    example:
      cod_uni_ou: "cod_uni_ou"
      cf: "cf"
      dat_val_canale_trasm_sfe: "dat_val_canale_trasm_sfe"
      cod_amm: "cod_amm"
      cod_aoo: "cod_aoo"
      des_ou: "des_ou"
      dt_verifca_cf: "dt_verifca_cf"
      stato_canale: "stato_canale"
  WS01Response_OU:
    properties:
      cod_uni_ou:
        type: "string"
        description: "Codice Univoco Ufficio destinatario di Fatturazione Elettroniche"
      des_ou:
        type: "string"
        description: "Denominazione Unita Organizzativa"
      stato_canale:
        type: "string"
        description: "A: Canale Attivo, V: In Fase di validazione"
    example:
      cod_uni_ou: "cod_uni_ou"
      des_ou: "des_ou"
      stato_canale: "stato_canale"
  WS01Response_data:
    properties:
      OU:
        type: "array"
        items:
          $ref: "#/definitions/WS01Response_OU"
        minItems: 1
      cod_amm:
        type: "string"
        description: "Codice Ente accreditato in IPA"
      des_amm:
        type: "string"
        description: "Denominazione Ente accreditato in IPA"
    example:
      OU:
      - cod_uni_ou: "cod_uni_ou"
        des_ou: "des_ou"
        stato_canale: "stato_canale"
      - cod_uni_ou: "cod_uni_ou"
        des_ou: "des_ou"
        stato_canale: "stato_canale"
      cod_amm: "cod_amm"
      des_amm: "des_amm"
  WS06Response_data:
    properties:
      cap:
        type: "string"
        description: "Cap registrato in IPA per la sede dell'UO"
      cf:
        type: "string"
        description: "Codice fiscale del servizio di faturazione"
      cod_amm:
        type: "string"
        description: "Codice Ente accreditato in IPA"
      cod_aoo:
        type: "string"
        description: "Codice AOO"
      cod_uni_ou:
        type: "string"
        description: "Codice Univoco dell'UO"
      cogn_resp:
        type: "string"
        description: "Cognome del responsabile dell'UO"
      comune:
        type: "string"
        description: "Comune registrato in IPA per la sede dell'UO"
      dat_val_canale_trasm_sfe:
        type: "string"
        description: "Data di inizio validità del servizio di fatturazione"
      des_ou:
        type: "string"
        description: "Nome dell'UO"
      dt_verifica_cf:
        type: "string"
        description: "Data di validazione del cf del servizio di fatturazione"
      fax:
        type: "string"
        description: "Numero di fax dell'UO"
      indirizzo:
        type: "string"
        description: "Indirizzo postale registrato in IPA per la sede dell'UO"
      mail1:
        type: "string"
        description: "Indirizzo email primario associato all’UO"
      mail2:
        type: "string"
        description: "Indirizzo email associato all’UO"
      mail3:
        type: "string"
        description: "Indirizzo email associato all’UO"
      mail_resp:
        type: "string"
        description: "Cognome del responsabile dell'UO"
      nome_resp:
        type: "string"
        description: "Nome del responsabile dell'UO"
      provincia:
        type: "string"
        description: "Provincia registrata in IPA per la sede dell'UO"
      regione:
        type: "string"
        description: "Regione registrata in IPA per la sede dell'UO"
      stato_canale:
        type: "string"
        description: "Stato del canale di fatturazione; A:Attivo|V=In fase di validazione"
      tel:
        type: "string"
        description: "Numero di telefono dell'UO"
      tel_resp:
        type: "string"
        description: "Cognome del responsabile dell'UO"
    example:
      cod_uni_ou: "cod_uni_ou"
      cf: "cf"
      mail_resp: "mail_resp"
      indirizzo: "indirizzo"
      nome_resp: "nome_resp"
      provincia: "provincia"
      regione: "regione"
      tel_resp: "tel_resp"
      mail3: "mail3"
      cap: "cap"
      comune: "comune"
      mail2: "mail2"
      mail1: "mail1"
      dat_val_canale_trasm_sfe: "dat_val_canale_trasm_sfe"
      cod_amm: "cod_amm"
      cod_aoo: "cod_aoo"
      des_ou: "des_ou"
      tel: "tel"
      cogn_resp: "cogn_resp"
      dt_verifica_cf: "dt_verifica_cf"
      fax: "fax"
      stato_canale: "stato_canale"
x-components:
  parameters:
    cod_amm:
      in: "query"
      name: "cod_amm"
      description: "COD_AMM"
      required: true
      type: "string"
      x-example: "c_c143"
